#! /bin/bash

NUM_IMG=0;

if [ $# != 4 ]; then
    printf "Not enough parameters !\n";
    printf "Here are the list of the 4 needed parameters :\n";
    printf " -> The number of measures you want to have.\n" #$1
    printf " -> The scan interval : i.e the interval between two different scans (in ms). \n" #$2
    printf " -> The scan window : the duration of each scan (in ms).\n" #3
    printf " -> The spacing between the receiver and the emitter (in M).\n" #4
    exit -1;
fi

if [ ! -e "./bin/hci_test" ]; then
    printf "Error : unexisting main program !\n";
    printf "You need to compile the program first by simply typing \"make\".\n"
    exit -1
fi

./bin/hci_test $1 $2 $3;
wait 

for i in $(find ./stats/figures/ -type f -name "*.png"); do
    NUM_IMG=$((${NUM_IMG} + 1));
done;

Rscript --no-save "./stats/RSSIStats.R" "./stats/res_rssi.txt" ${NUM_IMG} $2 $3 $4 > /dev/null 

exit 0